#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ ! -z $BLOCK_BUTTON ]; then
    amixer -D pulse set Master toggle > /dev/null
fi;

CARD="${1:-0}"
MIXER="${2:-default}" # use pulse for pulseaudio, default is alsa

PLAYBACK=`amixer -c $CARD -D $MIXER get Master | grep ": Playback"`;
PCT=`echo $PLAYBACK | egrep -o "[0-9]*%"`;
SOUND=`echo $PLAYBACK | egrep -o "\[o[fn]*\]" | egrep -o [onf]\*`;

echo "${PCT}";
echo "${PCT}";
if [ "$SOUND" = "off" ]; then
	echo "#FF0000";
fi;
