#!/usr/bin/python
# This Python file uses the following encoding: utf-8

import sys

from subprocess import Popen, call, PIPE

if len(sys.argv) > 1:
	button = int(sys.argv[1])
else:
	button = 0

def tvOn():
	p = Popen(["xrandr-tool current-resolution DP1"], shell=True, stdout=PIPE)
	output = p.stdout.readline()
	return (output != "")


if (button == 1):
	tvStatus = tvOn()
	if tvStatus:
		call(["xrandr --output DP1 --off"], shell=True)
	else:
		call(["xrandr --auto"], shell=True)
		call(["xrandr --output DP1 --above eDP1"], shell=True)

tvStatus = tvOn()
if (tvStatus):
	output = "ON"
else:
	output = "OFF"

print output
print output
