#!/usr/bin/python
# This python file uses the following encoding: utf-8

import urllib2, sys, getopt
from bs4 import BeautifulSoup

#import pprint

def usage():
    print "Example usage: i3blocks_precipitation"

def main(argv):
    try:
        url="http://api.met.no/weatherapi/nowcast/0.9/?lat=63.4299;lon=10.3961"

        graph = ["▁", "▂", "▃", "▄", "▅", "▆", "▇"]

        soup = BeautifulSoup(urllib2.urlopen(url).read(), "lxml")
        forecasts = soup.find('product').find_all('time')
        values = []
        maxValue = 0
        for f in forecasts:
            f = float(f.find('precipitation')['value'].encode('utf-8'))
            values.append(f)
            maxValue = f if f > maxValue else maxValue

        txt = ""
        for precipitation in values:
            graphPos = 0 if precipitation == 0.0 else max(1, int( min(1, precipitation / maxValue) * (len(graph)) )) - 1
            txt = txt + graph[graphPos]

        txt += " (max: " + str(maxValue) + " mm/h)"
        print txt
        print txt

    except getopt.GetoptError,e:
        print e
        usage()
        sys.exit(2)

if __name__ == '__main__':
    main(sys.argv[1:])
