#!/usr/bin/python
# This python file uses the following encoding: utf-8

import libxml2
import urllib
import sys
import codecs
import md5
import webbrowser
try:
    url = sys.argv[1]

    m = md5.new(url)
    filename = '/tmp/i3blocksrss_' + m.hexdigest()
    maxLength = 50
    if len(sys.argv) > 2:
        f = open(filename, 'r')
        webbrowser.open(f.read())
        f.close()

    rss = libxml2.parseDoc(urllib.urlopen(url).read())

    titles = rss.xpathEval('/rss/channel/item/title')
    urls = rss.xpathEval('/rss/channel/item/link')

    f = open(filename, 'w')
    f.write(urls[0].content)
    f.close()

    text = titles[0].content.decode('utf-8', 'ignore')
    if len(text) > maxLength:
        text = text[:maxLength] + u'…'

    print text.encode('utf-8', 'ignore')
    print text.encode('utf-8', 'ignore')
except Error as e:
    print "Error({0})".format(e)
    print "Error({0})".format(e)
