#!/usr/bin/python
# This Python file uses the following encoding: utf-8

import sys

from subprocess import Popen, call, PIPE

monitorID = sys.argv[1]
settings = sys.argv[2]
button = int(sys.argv[3]) if len(sys.argv) > 3 else 0

def monitorOn():
	p = Popen(["xrandr-tool current-resolution " + monitorID], shell=True, stdout=PIPE)
	return (p.stdout.readline() != "")

if (button == 1):
	if monitorOn():
		call(["xrandr --output " + monitorID + " --off"], shell=True)
	else:
		call(["xrandr --auto"], shell=True)
		call(["xrandr --output " + monitorID + " " + settings], shell=True)

output = "OFF" if monitorOn() else "ON"

print output
print output
