#!/usr/bin/python
# This Python file uses the following encoding: utf-8

import json
import sys
import urllib
import webbrowser
import time


pieces = {
    "bk": "♔",
    "bq": "♕",
    "br": "♖",
    "bb": "♗",
    "bn": "♘",
    "bp": "♙",
    "wk": "♚",
    "wq": "♛",
    "wr": "♜",
    "wb": "♝",
    "wn": "♞",
    "wp": "♟"
}


apibase = "http://snutt.nrk.no/sport_apps/sjakk/api/zugzwang/"

data = urllib.urlopen(apibase + "fetch-games/2")
games = json.loads(data.read(), "utf-8")
gameId = games["games"][len(games["games"]) - 1]["gameId"]

data = urllib.urlopen(apibase + "game/" + str(gameId))
game = json.loads(data.read(), "utf-8")

moves = []
moveColor = "w"
if game["engine"]:
    moves = game["engine"]["moves"]
    moveColor = moves[0]["color"]


def getTime(ms):
    if (ms < 0):
        ms = 0
    s = ms/1000
    return str(int(s/60)) + ":" + "%02d" % (s % 60,)

text = [str(int(game["move"] / 2) + 1) + moveColor + " ( w: " + getTime(game["clock"]["white"]) + ", b: " + getTime(game["clock"]["black"]) + " )"]
for move in moves:
    text.append(pieces[move["color"] + move["piece"]].decode("utf-8") + " " + move["from"] + " → ".decode("utf-8") + move["to"] + "  (" + (str(move["engineScore"])) + ")")

print "  |  ".join(text).encode("utf-8")
print "  |  ".join(text).encode("utf-8");
